pub mod create_event;
pub mod create_manual_activity;
pub mod delete_activity;
pub mod get_activity;
pub mod get_activity_best_efforts;
pub mod get_activity_streams;
pub mod get_athlete;
pub mod get_athlete_profile;
pub mod get_athlete_training_plan;
pub mod get_weather_forecast;
pub mod get_workout;
pub mod list_activities;
pub mod list_activity_intervals;
pub mod list_activity_messages;
pub mod list_athlete_hr_curves;
pub mod list_athlete_pace_curves;
pub mod list_athlete_power_curves;
pub mod list_athlete_routes;
pub mod list_chats;
pub mod list_events;
pub mod list_folders;
pub mod list_gear;
pub mod list_sport_settings;
pub mod list_wellness;
pub mod list_workouts;
pub mod post_activity_message;
pub mod search_activities;
pub mod update_activity;

#[cfg(test)]
pub const TEST_AUTH_HEADER: &str = "Basic QVBJX0tFWTp0ZXN0LWFwaS1rZXk=";
