name: Secretlint

on:
  pull_request:
  push:
    branches: main

jobs:
  secretlint:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5
        with:
          package_json_file: package.json
      - run: pnpx @secretlint/quick-start "**/*"
